create table Product_info as select P_no,p_name from PRODUCT_MASTER_2;
select * from Product_info;

create table Product_Price as select COST_PRICE,SELL_PRICE,PROFIT,QTY from PRODUCT_MASTER_2;
select * from Product_Price;

CREATE TABLE TOP_EARNER 
AS
SELECT * FROM CUSTOMER_MASTER WHERE 1=2;

CREATE TABLE MID_EARNER 
AS
SELECT * FROM CUSTOMER_MASTER WHERE 1=2;

CREATE TABLE LOW_EARNER 
AS
SELECT * FROM CUSTOMER_MASTER WHERE 1=2;

INSERT ALL 
WHEN SALARY >=5000
THEN
INTO TOP_EARNER 
WHEN
SALARY BETWEEN 3000 AND 5000
THEN 
INTO MID_EARNER
WHEN SALARY<3000
THEN
INTO LOW_EARNER
SELECT * FROM CUSTOMER_MASTER;

SELECT * FROM TOP_EARNER;
SELECT * FROM MID_EARNER;
SELECT * FROM LOW_EARNER;

